In [2]:
import os
import numpy as np

## Swath_Sampling

In [3]:
orbit = np.load("C:/Users/james/Projects/SURF_2024/odysea-science-simulator/odysim/orbit_files/orbit_out_2020_2023_height590km.npz")
orbit

NpzFile 'C:/Users/james/Projects/SURF_2024/odysea-science-simulator/odysim/orbit_files/orbit_out_2020_2023_height590km.npz' with keys: orbit_cut_points, time_stamp_vector, coarse_x, coarse_y, coarse_z...

In [4]:
cut_points = orbit['orbit_cut_points']
cut_points

array([     24,     120,     217, ..., 1576937, 1577033, 1577130],
      dtype=int64)

In [5]:
for array in orbit:
    # Can itterate through npz file like this, where itterable is a list of keys for each array
    print(array)
    print(np.shape(orbit[array]))

orbit_cut_points
(16341,)
time_stamp_vector
(1577120,)
coarse_x
(1577120,)
coarse_y
(1577120,)
coarse_z
(1577120,)
coarse_s
(1577120,)


In [6]:
print(cut_points)
np.where((cut_points > 5000) & (cut_points < 6000))

[     24     120     217 ... 1576937 1577033 1577130]


(array([52, 53, 54, 55, 56, 57, 58, 59, 60, 61], dtype=int64),)

In [7]:
print(cut_points[52])
print(cut_points[61])

5043
5911


In [14]:
c_bins = np.arange(-5, 6, 1)
swath_width = 1
c_bins

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [15]:
np.abs(c_bins)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5])

In [16]:
np.nanmax(c_bins)

5

In [17]:
swath_blanking = (np.abs(c_bins) > np.nanmax(c_bins) - swath_width*1) | (np.abs(c_bins) < swath_width*1)
swath_blanking

array([ True, False, False, False, False,  True, False, False, False,
       False,  True])

In [19]:
empty = np.zeros(5)
empty

array([0., 0., 0., 0., 0.])

In [21]:
empty2 = np.zeros((3, 2))
empty2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.nan * empty2

array([[nan, nan],
       [nan, nan],
       [nan, nan]])