In [2]:
import os
import numpy as np
import xarray as xr

## Swath_Sampling

In [29]:
orbit = np.load("C:/Users/james/Projects/SURF_2024/odysea-science-simulator/odysim/orbit_files/orbit_out_2020_2023_height590km.npz")
orbit

NpzFile 'C:/Users/james/Projects/SURF_2024/odysea-science-simulator/odysim/orbit_files/orbit_out_2020_2023_height590km.npz' with keys: orbit_cut_points, time_stamp_vector, coarse_x, coarse_y, coarse_z...

In [30]:
cut_points = orbit['orbit_cut_points']
cut_points

array([     24,     120,     217, ..., 1576937, 1577033, 1577130],
      dtype=int64)

In [31]:
for array in orbit:
    # Can itterate through npz file like this, where itterable is a list of keys for each array
    print(array)
    print(np.shape(orbit[array]))

orbit_cut_points
(16341,)
time_stamp_vector
(1577120,)
coarse_x
(1577120,)
coarse_y
(1577120,)
coarse_z
(1577120,)
coarse_s
(1577120,)


In [32]:
print(cut_points)
np.where((cut_points > 5000) & (cut_points < 6000))

[     24     120     217 ... 1576937 1577033 1577130]


(array([52, 53, 54, 55, 56, 57, 58, 59, 60, 61], dtype=int64),)

In [33]:
print(cut_points[52])
print(cut_points[61])

5043
5911


In [34]:
print(orbit['time_stamp_vector'][0:10])

[1.57786506e+09 1.57786512e+09 1.57786518e+09 1.57786524e+09
 1.57786530e+09 1.57786536e+09 1.57786542e+09 1.57786548e+09
 1.57786554e+09 1.57786560e+09]


In [14]:
c_bins = np.arange(-5, 6, 1)
swath_width = 1
c_bins

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [15]:
np.abs(c_bins)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5])

In [16]:
np.nanmax(c_bins)

5

In [17]:
swath_blanking = (np.abs(c_bins) > np.nanmax(c_bins) - swath_width*1) | (np.abs(c_bins) < swath_width*1)
swath_blanking

array([ True, False, False, False, False,  True, False, False, False,
       False,  True])

In [19]:
empty = np.zeros(5)
empty

array([0., 0., 0., 0., 0.])

In [21]:
empty2 = np.zeros((3, 2))
empty2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.nan * empty2

array([[nan, nan],
       [nan, nan],
       [nan, nan]])

In [7]:
test = np.arange(0, 10)
mask_test = np.where(test % 2 == 0, np.nan, test)
mask_test

array([nan,  1., nan,  3., nan,  5., nan,  7., nan,  9.])

In [8]:
mask_test[np.isnan(mask_test)] = 0
mask_test

array([0., 1., 0., 3., 0., 5., 0., 7., 0., 9.])

In [26]:
ds = xr.Dataset()
base = np.empty(shape=(3,2))
x, y = np.shape(base)
ds

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*

In [27]:
ds = ds.assign_coords(coords={'along_track': (np.arange(0,x)),
                                      'cross_track': (np.arange(0,y))})   


In [28]:
ds

<xarray.Dataset>
Dimensions:      (along_track: 3, cross_track: 2)
Coordinates:
  * along_track  (along_track) int32 0 1 2
  * cross_track  (cross_track) int32 0 1
Data variables:
    *empty*

In [3]:
errors = np.load("C:/Users/james/Projects/SURF_2024/odysea-science-simulator/odysim/uncertainty_tables/odysea_sigma_vr_lut_height590km_look52deg_swath1672km.npz")
errors

NpzFile 'C:/Users/james/Projects/SURF_2024/odysea-science-simulator/odysim/uncertainty_tables/odysea_sigma_vr_lut_height590km_look52deg_swath1672km.npz' with keys: sigma_vr

In [7]:
for array_key in errors:
    print(array_key)
    print(np.shape(errors[array_key]))

sigma_vr
(200, 78, 76)


In [5]:
errors['sigma_vr']

array([[[10.99200043,  8.12079037,  7.55781056, ...,  8.12079037,
          7.55781056,  8.25714141],
        [10.97550913,  8.08494493,  7.50404689, ...,  8.08494493,
          7.50404689,  8.17897193],
        [10.99200043,  8.07284064,  7.4709233 , ...,  8.07284064,
          7.4709233 ,  8.12079037],
        ...,
        [11.04083749,  8.08494493,  7.45973813, ...,  8.08494493,
          7.45973813,  8.08494493],
        [11.12010606,  8.12079037,  7.4709233 , ...,  8.12079037,
          7.4709233 ,  8.07284064],
        [11.2266069 ,  8.17897193,  7.50404689, ...,  8.17897193,
          7.50404689,  8.08494493]],

       [[10.99200043,  8.12079037,  7.55781056, ...,  8.12079037,
          7.55781056,  8.25714141],
        [10.97550913,  8.08494493,  7.50404689, ...,  8.08494493,
          7.50404689,  8.17897193],
        [10.99200043,  8.07284064,  7.4709233 , ...,  8.07284064,
          7.4709233 ,  8.12079037],
        ...,
        [11.04083749,  8.08494493,  7.45973813, ...,  

In [9]:
test = np.nan*np.ones((2,3))
test

array([[nan, nan, nan],
       [nan, nan, nan]])